"""E25 measurement — opt-in "sharp mode" for the 11 named manager bots
(owner-directed 2026-08-06: "Build sharp mode").

Change under test (deck engine, OFF by default): from round SHARP_R0=8 on,
a manager stops feeding categories he has already conceded (roster z-sum
<= SHARP_DEAD) and pays up for the ones still in reach, weighting the
weakest live category hardest (SHARP_W scales the term). adp_w, val_w,
noise, bias and loyalty are untouched — personality preserved, only
competence moves.

Method: full mock drafts generated by the DECK'S OWN AI in a fake DOM
(scratchpad room_run.js = C_prelude + the deck's engine/data/judgment
blocks + room_driver.js), CRN-paired — for each (seed, slot) the default
and sharp rooms share the seed, the cast shuffle, and the owner policy, so
the ONLY difference is bot competence. Rosters are then graded by the v2
instrument, 18,000 seasons each (6,000 x seeds 11/23/47).

Owner policy per room, held identical across arms:
  "card" — the owner seat follows the shipped Top-5 #1 every turn.
  "m40"  — the owner seat takes his mock-40 picks in order when still
           available, else the card's #1 (ownerGot records how many landed).

BAR (registered in SEPTEMBER-PLAN E25 BEFORE this run; applied as written):
  (1) SHARPER  — over >=6 fresh rooms, mean bot dead-kept-cats <= 0.8
                 (default baseline 1.64) AND mean bot ECW +>= 0.05/wk.
  (2) HARDER   — the owner's champ% drops by >= 3pp in sharp rooms under
                 the same owner policy.
  (3) REALISM  — default-mode behavior byte-identical to pre-E25 (verified
                 separately by the parity harness: same rooms, same picks).

Fresh clone: `python3 arena/mocks/e25_measurement.py` (needs node and the
scratchpad room runner; ROOM_RUNNER env overrides its path) ->
arena/results/e25_measurement_out.json
"""

import itertools
import json
import os
import random
import subprocess
import sys

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
os.chdir(REPO)
os.environ["ARENA_WEEK_MODEL"] = "daily"  # v2 epoch
sys.path = [os.path.join(REPO, "scripts"), os.path.join(REPO, "arena")] + [
    p for p in sys.path if p not in (os.path.join(REPO, "scripts"),
                                     os.path.join(REPO, "arena"))]

import hoops  # noqa: E402
import arena  # noqa: E402

players = hoops.zscores(hoops.load_players())
byname = {p["player"]: p for p in players}
CATS = hoops.CATS

RUNNER = os.environ.get(
    "ROOM_RUNNER",
    "/tmp/claude-0/-home-user-yahoo-fantasy-basketball/"
    "58588377-022f-59e5-ac2c-106514acd881/scratchpad/room_run.js")
HEAD_SEEDS = [11, 23, 47]
HEAD_N = 6000

# 8 rooms: seeds x slots spread across the snake, two owner policies.
ROOMS = [
    (101, 4, "m40", "3PTM,TO,FT%"),
    (202, 1, "card", ""),
    (303, 6, "card", "FT%,3PTM,TO"),
    (404, 12, "card", ""),
    (505, 8, "card", "FT%,3PTM,PTS"),
    (606, 3, "card", ""),
    (707, 10, "card", "FT%,AST,3PTM"),
    (808, 4, "m40", ""),
]
M40 = "|".join(p["player"] for p in json.load(
    open("arena/data/states/draft_state_mock40.json"))["picks"] if p["slot"] == 4)


def gen_room(seed, slot, sharp, policy, punt):
    env = dict(os.environ, ROOM_SEED=str(seed), ROOM_SLOT=str(slot),
               ROOM_SHARP="1" if sharp else "0", ROOM_OWNER_POLICY=policy,
               ROOM_PUNT=punt, ROOM_M40=M40)
    r = subprocess.run(["node", RUNNER], capture_output=True, text=True, env=env)
    if r.returncode != 0:
        raise RuntimeError(f"room gen failed {seed}/{slot}/{sharp}: {r.stderr[-400:]}")
    return json.loads(r.stdout.strip().splitlines()[-1])


def grade(room):
    """v2 season sim + per-seat category diagnostics."""
    slot = room["slot"]
    ros = {}
    for pk in room["picks"]:
        ros.setdefault(pk["slot"], []).append(byname[pk["player"]])
    for s in range(1, 13):
        assert len(ros[s]) == 13, (room["seed"], s, len(ros[s]))
    tc = {s: 0 for s in ros}
    tp = {s: 0 for s in ros}
    for sd in HEAD_SEEDS:
        champs, plyf = arena.simulate_seasons(ros, HEAD_N, random.Random(sd))
        for s in ros:
            tc[s] += champs[s]
            tp[s] += plyf[s]
    T = HEAD_N * len(HEAD_SEEDS)
    seats = {}
    for s in range(1, 13):
        z = {c: sum(p["z"][c] for p in ros[s]) for c in CATS}
        bz, bp = max(((sum(z[c] for c in CATS if c not in pu), pu)
                      for pu in itertools.combinations(CATS, 3)), key=lambda r: r[0])
        kept = [c for c in CATS if c not in bp]
        mu, va = arena.team_week_model(ros[s])
        seats[s] = {
            "champ": round(100.0 * tc[s] / T, 3),
            "playoff": round(100.0 * tp[s] / T, 3),
            "dead_kept": sum(1 for c in kept if z[c] < 0),
            "live_cats": sum(1 for c in CATS if z[c] > 0),
            "best_punt": sorted(bp), "best_z": round(bz, 2),
            "roster": [p["player"] for p in ros[s]],
        }
    ecw = ecw_all(ros)
    for s in seats:
        seats[s]["ecw"] = ecw[s]
    return {"owner_slot": slot, "seats": seats,
            "owner": seats[slot],
            "bots": [seats[s] for s in range(1, 13) if s != slot]}


def ecw_all(ros):
    """expected categories won/week vs the rest of the room (pairwise mean)."""
    import math
    models = {s: arena.team_week_model(r) for s, r in ros.items()}
    out = {}
    for a in ros:
        tot = 0.0
        n = 0
        for b in ros:
            if a == b:
                continue
            ma, va = models[a]
            mb, vb = models[b]
            w = 0.0
            for c in CATS:
                d = (ma[c] - mb[c]) / (math.sqrt(va[c] + vb[c]) or 1e-9)
                pr = 0.5 * (1 + math.erf(d / math.sqrt(2)))
                w += (1 - pr) if c == "TO" else pr
            tot += w
            n += 1
        out[a] = round(tot / n, 3)
    return out


def main():
    only = os.environ.get("E25_ROOMS")
    rooms = [r for r in ROOMS if not only or str(r[0]) in only.split(",")]
    results = {}
    for seed, slot, policy, punt in rooms:
        key = f"{seed}_{slot}"
        print(f"=== room {key} ({policy}, punt={punt or 'none'}) ===", flush=True)
        entry = {"seed": seed, "slot": slot, "policy": policy, "punt": punt}
        for arm, sharp in (("default", False), ("sharp", True)):
            room = gen_room(seed, slot, sharp, policy, punt)
            g = grade(room)
            g["owner_got"] = room["ownerGot"]
            g["cast"] = room["cast"]
            entry[arm] = g
            bots = g["bots"]
            print(f"  {arm:8s} owner {g['owner']['champ']:6.2f} | bot dead-kept "
                  f"{sum(b['dead_kept'] for b in bots)/11:.2f} | bot ECW "
                  f"{sum(b['ecw'] for b in bots)/11:.3f}", flush=True)
        results[key] = entry
    tag = os.environ.get("E25_TAG", "")  # "b" -> e25b_* (frame-declaring variant)
    stem = f"arena/results/e25{tag}_measurement_out"
    path = f"{stem}.json" if not only else f"{stem}_{only.replace(',', '_')}.json"
    json.dump(results, open(path, "w"), indent=1)
    print("wrote", path)


if __name__ == "__main__":
    main()
